{
  "openapi":"3.0.2",
  "info": {
    "title":"Meetapp",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/meetapp-api/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/sessions": {
      "post": {
        "tags": ["Sessions"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "User",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Authenticates user, return a Bearer Token and user's id and email",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    },
                    "user": {
                      "$ref": "#/components/schemas/User"
                    }
                  }
                },
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsImlhdCI6MTYzMjE3NzUwNywiZXhwIjoxNjMyNzgyMzA3fQ.PXAPALSkvZfUNkV5g-0xjIXJmGugXkZPd1CUHRK9m18",
                  "user": {
                    "id": 33,
                    "email": "johndoe@example.com",
                    "name": "John Doe"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token not provided",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "example": {
                  "statusCode": 401,
                  "error": "Unauthorized",
                  "message": "Token not provided",
                  "attributes": {
                    "code": 441,
                    "error": "Token not provided"
                  },
                  "docs": "https://github.com/DiegoVictor/meetapp-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "name",
                  "password"
                ],
                "title": "User",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com",
                "name": "John Doe",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create new users",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": 32,
                  "email": "johndoe@example.com",
                  "name": "John Doe"
                }
              }
            }
          },
          "400": {
            "description": "Email already in use",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "Email already in use",
                  "code": 341,
                  "docs": "https://github.com/DiegoVictor/meetapp-api#errors-reference"
                }
              }
            }
          }
        }
      },
    },
  },
  "components": {
    "schemas": {
      "User": {
        "properties": {
          "id": {
            "type": "integer"
          },
          "email": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "Error": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      },
      "Unauthorized": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "attributes": {
            "type": "object",
            "properties": {
              "code": {
                "type": "integer"
              },
              "error": {
                "type": "string"
              }
            }
          },
          "docs": {
            "type": "string"
          }
        }
      }
    },
  }
}
